### ISSUE TITLE
Docker image requires 'shinythemes'

### ISSUE THREAD

**Issue by gringer** [yueqiw/shiny_cell_browser#8]
Error message seen:

```
An error has occurred!

there is no package called â€˜shinythemesâ€™
```

I added the following to the Dockerfile:

    RUN R -e 'install.packages(c("shinythemes"))'

This allowed the application to start, but the log also reported an error about the 'logging' package, so I also added:

    RUN R -e 'install.packages(c("logging"))'

**Comment by yueqiw** [comment]
Thanks for pointing this out! I updated the docker file with what you suggested. 

I haven't been using docker for a while. What I ended up doing was to make sure the app runs locally in Rstudio, and then deploy it on shinyapps.io following the instruction here: https://shiny.rstudio.com/articles/shinyapps.html
